/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Sends a confirmation link by email and a 6-digit code by SMS, and sets
         *     the session cookie. The account can be used once both are confirmed.
         */
        post: operations["authSignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the email with the token from the emailed link
         * @description Needs no session; the link may be opened on another device. Opening it twice is fine.
         */
        post: operations["authConfirmEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the phone with the 6-digit code
         * @description Five wrong tries end the code; ask for a new one with /auth/resend.
         */
        post: operations["authConfirmPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a new email link or phone code
         * @description At most one a minute and five an hour. A new code replaces the old one.
         */
        post: operations["authResend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email or phone and password */
        post: operations["authSignin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out; clears session cookie */
        post: operations["authSignout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password reset code to the account's phone
         * @description Answers 204 whether or not the account exists.
         */
        post: operations["authForgot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password using the reset code
         * @description Signs the account out on every device.
         */
        post: operations["authReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own profile and today's limits */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update settings (timezone, country, etc.) */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Free, Starter and Pro with their prices
         * @description Signed-in reps also get intro_eligible (the intro price is for a first paid plan only).
         */
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The rep's plan, next renewal and any booked change */
        get: operations["getSubscription"];
        put?: never;
        /**
         * Change plan
         * @description Moving up starts now and is paid from the balance today: the first
         *     month from Free, or the difference for the rest of the month between
         *     paid plans. Moving down (including to Free) is booked for the next
         *     renewal; the rep keeps what they paid for until then. Choosing the
         *     current plan cancels a booked move.
         */
        post: operations["changeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What a change of plan would cost, without making it */
        post: operations["quoteSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balance, money held for calls, this month's spending, and the first page of activity */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** More activity, newest first (holds are not listed) */
        get: operations["getWalletActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One month's statement as CSV, in the rep's time zone, with exact amounts */
        get: operations["getWalletStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/topups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a card top-up
         * @description Opens a checkout with Paystack (cards from Nigeria, Ghana, Kenya) or
         *     Stripe (everyone else); the server picks by the rep's country. Nothing
         *     reaches the balance until the provider's signed webhook confirms the
         *     payment. Needs confirmed email and phone.
         */
        post: operations["startTopup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/topups/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where a top-up is, for the page the rep returns to */
        get: operations["getTopup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search available numbers by area code */
        get: operations["searchNumbers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/numbers/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rented numbers */
        get: operations["listMyNumbers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/numbers/{numberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a rented number */
        delete: operations["cancelNumber"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/numbers/{numberId}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set as default outbound number */
        put: operations["setDefaultNumber"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The rep's lead lists with progress, newest first */
        get: operations["listLeadLists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a list and its leads (refused once any lead was called) */
        delete: operations["deleteLeadList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read a CSV and say what uploading it would add and leave out
         * @description Without a mapping, the server suggests one from the column names.
         *     A mapping that can't be used yet (no phone column) comes back as
         *     `problem`, with the columns, so the rep can fix it. Nothing is saved.
         */
        post: operations["checkImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a CSV as a new list
         * @description Everything is checked again on the server. US and Canada numbers go
         *     into the named list; numbers elsewhere go into a second list named
         *     "<name> · outside US and Canada".
         */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The rep's scripts, most recently changed first */
        get: operations["listScripts"];
        put?: never;
        /** Save a new script */
        post: operations["createScript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scripts/{scriptId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scriptId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Replace a script's name and parts, and which lists use it */
        put: operations["updateScript"];
        post?: never;
        /** Delete a script; lists that used it are left without one */
        delete: operations["deleteScript"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a call */
        post: operations["startCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{callId}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save call outcome */
        post: operations["saveOutcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{callId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End a call early */
        post: operations["endCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialer/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start auto-dial session (Starter/Pro) */
        post: operations["startDialer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialer/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause auto-dial */
        post: operations["pauseDialer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialer/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip current lead */
        post: operations["skipDialer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialer/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop auto-dial session */
        post: operations["stopDialer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List follow-ups (today, tomorrow, later) */
        get: operations["listFollowups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full call log */
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{callId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recording metadata (Pro) */
        get: operations["getRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kyc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get KYC status */
        get: operations["getKycStatus"];
        put?: never;
        /** Start ID and face check */
        post: operations["startKyc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a QR pairing code (laptop side) */
        post: operations["createPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairing/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join as phone audio leg using pairing code */
        post: operations["joinPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/telnyx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telnyx call events webhook */
        post: operations["telnyxWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/paystack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paystack payment webhook
         * @description Checked with x-paystack-signature (HMAC-SHA512 of the body) before anything is read. A repeated webhook never credits twice.
         */
        post: operations["paystackWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe payment webhook
         * @description Checked with Stripe-Signature (HMAC-SHA256, 5-minute window) before anything is read. A repeated webhook never credits twice.
         */
        post: operations["stripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/smileid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Smile ID result webhook */
        post: operations["smileidWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/kyc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending KYC checks */
        get: operations["adminListKyc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Every error has this shape. `error` is shown to the rep as is. */
        ErrorBody: {
            error: string;
            /** @description Stable machine-readable reason, e.g. "code_wrong" */
            code: string;
            fields?: {
                [key: string]: string;
            };
        };
        SignupRequest: {
            /** @description Full name as on the rep's ID; the card name must match it */
            name: string;
            /** Format: email */
            email: string;
            /** @description With country code, e.g. "+234 803 123 4567"; stored as E.164 */
            phone: string;
            password: string;
            /** @description ISO 3166-1 alpha-2 */
            country: string;
            /** @description IANA zone, e.g. "Africa/Lagos". Defaults to UTC. */
            timezone?: string;
            /** @description Must be true */
            accept_rules: boolean;
        };
        SigninRequest: {
            /** @description Email or phone number */
            login: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            user_id: string;
            name: string;
            email: string;
            phone: string;
            country: string;
            timezone: string;
            email_confirmed: boolean;
            phone_confirmed: boolean;
            /** @description Both email and phone confirmed */
            confirmed: boolean;
            /** Format: date-time */
            rules_accepted_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        MeResponse: components["schemas"]["User"] & {
            /** @enum {string} */
            plan: "free" | "starter" | "pro";
            /**
             * Format: int64
             * @description What the rep can spend now. 1 USD = 1,000,000.
             */
            balance_microdollars: number;
            /**
             * Format: int64
             * @description Set aside for calls in progress; already taken off the balance
             */
            held_microdollars: number;
        };
        SettingsRequest: {
            timezone?: string;
            country?: string;
        };
        Plan: {
            /** @enum {string} */
            id: "free" | "starter" | "pro";
            /** Format: int64 */
            monthly_fee_microdollars: number;
            /** Format: int64 */
            intro_fee_microdollars: number;
            intro_months: number;
            /** @description Call price = provider cost × this ÷ 100 */
            rate_multiplier_pct: number;
            /** Format: int64 */
            us_price_per_minute_microdollars: number;
            dials_per_day: number | null;
            features: string[];
        };
        Subscription: {
            /** @enum {string} */
            plan: "free" | "starter" | "pro";
            /** Format: date-time */
            started_at?: string;
            /** Format: date */
            intro_ends_on?: string | null;
            /** Format: date */
            next_renewal?: string;
            /** @description Plan the rep moves to at next_renewal */
            pending_change?: string | null;
            /** Format: int64 */
            next_charge_microdollars?: number;
            /** Format: date-time */
            renewal_failed_at?: string | null;
            /**
             * Format: date-time
             * @description Top up before this or move to Free
             */
            grace_ends_at?: string | null;
        };
        PlanChangeRequest: {
            /** @enum {string} */
            plan_id: "free" | "starter" | "pro";
        };
        PlanQuote: {
            from: string;
            to: string;
            /** @enum {string} */
            kind: "upgrade" | "downgrade" | "stay";
            /** Format: int64 */
            due_today_microdollars: number;
            intro_price: boolean;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            next_renewal: string | null;
            /** Format: int64 */
            next_charge_microdollars: number;
            /** Format: int64 */
            balance_microdollars: number;
            /** Format: int64 */
            balance_after_microdollars: number;
        };
        WalletResponse: {
            /**
             * Format: int64
             * @description What the rep can spend now. 1 USD = 1,000,000.
             */
            balance_microdollars: number;
            /** Format: int64 */
            held_microdollars: number;
            spent_this_month: {
                /** Format: int64 */
                calls: number;
                /** Format: int64 */
                plan: number;
                /** Format: int64 */
                numbers: number;
                /** Format: int64 */
                total: number;
            };
            activity: components["schemas"]["LedgerEntry"][];
            next_cursor: string;
            /** Format: int64 */
            min_topup_microdollars: number;
            /** Format: int64 */
            max_topup_microdollars: number;
            /** @enum {string} */
            topup_provider: "paystack" | "stripe";
        };
        LedgerEntry: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "topup" | "call" | "number" | "plan" | "refund";
            /**
             * Format: int64
             * @description Positive in, negative out
             */
            amount_microdollars: number;
            description: string;
            /** Format: date-time */
            created_at: string;
        };
        TopupRequest: {
            /**
             * Format: int64
             * @description Whole cents ($5 to $500)
             */
            amount_microdollars: number;
        };
        TopupResponse: {
            reference: string;
            payment_url: string;
            /** @enum {string} */
            provider: "paystack" | "stripe";
            /** Format: int64 */
            amount_microdollars: number;
        };
        AvailableNumber: {
            number?: string;
            area_code?: string;
            city?: string;
            monthly_price_usd?: number;
        };
        RentedNumber: {
            /** Format: uuid */
            id?: string;
            number?: string;
            city?: string;
            is_default?: boolean;
            monthly_price_usd?: number;
            /** Format: date */
            renews_at?: string;
        };
        LeadList: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            region: "us_ca" | "abroad";
            /** @enum {string} */
            status: "new" | "active" | "done" | "abroad";
            lead_count: number;
            /** @description Leads called at least once */
            called_count: number;
            /** @description Follow-ups not done yet */
            followup_count: number;
            script: {
                /** Format: uuid */
                id: string;
                name: string;
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description What a CSV column is saved as. full_name is split into first and last name.
         * @enum {string}
         */
        LeadField: "first_name" | "last_name" | "full_name" | "company" | "phone" | "email" | "city" | "notes" | "skip";
        ImportRequest: {
            /** @description The file's text, up to 2 MB and 5,000 rows */
            csv: string;
            /** @description One field per column, in column order */
            mapping?: components["schemas"]["LeadField"][];
            name?: string;
        };
        ImportCheck: {
            columns: {
                header: string;
                /** @description The first value in the column */
                sample: string;
                field: components["schemas"]["LeadField"];
            }[];
            /** @description Lead rows in the file (blank lines don't count) */
            rows: number;
            /** @description US and Canada leads that would go into the list */
            ready: number;
            /** @description Leads that would go into the separate list */
            abroad: number;
            /** @description Rows not added to the list, by reason */
            left_out: {
                invalid: number;
                premium: number;
                duplicate: number;
                dnc: number;
                listed: number;
                abroad: number;
            };
            /** @description The first 200 rows not added */
            left_out_rows: components["schemas"]["LeftOutRow"][];
            /** @description Why the mapping can't be used yet; counts are zero until it's fixed */
            problem: {
                code: string;
                error: string;
            } | null;
        };
        LeftOutRow: {
            /** @description Line in the file; the header is line 1 */
            row: number;
            name: string;
            /** @description As written in the file */
            phone: string;
            /** @enum {string} */
            reason: "invalid" | "premium" | "duplicate" | "dnc" | "listed" | "abroad";
            /** @description For a duplicate, the line it repeats */
            same_as_row: number | null;
            /** @description For a number already listed, the list it's in */
            list_name: string | null;
        };
        ScriptPart: {
            title: string;
            /** @description Text with fill-in words in curly brackets, like {first_name} */
            body: string;
        };
        Script: {
            /** Format: uuid */
            id: string;
            name: string;
            parts: components["schemas"]["ScriptPart"][];
            /** @description Lead lists that use this script */
            lists: {
                /** Format: uuid */
                id: string;
                name: string;
            }[];
            /** Format: date-time */
            updated_at: string;
        };
        ScriptRequest: {
            name: string;
            parts: components["schemas"]["ScriptPart"][];
            /** @description Exactly the lists that use the script after saving. Leave out to keep them as they are. */
            list_ids?: string[];
        };
        StartCallRequest: {
            /** Format: uuid */
            lead_id: string;
            /** Format: uuid */
            from_number_id: string;
            /**
             * @default laptop
             * @enum {string}
             */
            device: "laptop" | "phone" | "linked";
        };
        StartCallResponse: {
            /** Format: uuid */
            call_id?: string;
            telnyx_token?: string;
            telnyx_call_id?: string;
        };
        OutcomeRequest: {
            /**
             * @description 1=interested, 2=callback, 3=not interested, 4=voicemail, 5=no answer, 6=wrong number
             * @enum {string}
             */
            outcome: "1" | "2" | "3" | "4" | "5" | "6";
            note?: string;
            /** Format: date-time */
            followup_at?: string | null;
        };
        Followup: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            lead_id?: string;
            lead_name?: string;
            lead_phone?: string;
            /** Format: date-time */
            due_at?: string;
            reason?: string;
        };
        HistoryResponse: {
            calls?: components["schemas"]["CallRecord"][];
            total?: number;
            page?: number;
        };
        CallRecord: {
            /** Format: uuid */
            call_id?: string;
            lead_name?: string;
            lead_phone?: string;
            from_number?: string;
            /** Format: date-time */
            started_at?: string;
            seconds?: number;
            /** Format: int64 */
            cost_microdollars?: number;
            outcome?: string;
            note?: string;
        };
        Recording: {
            /** Format: uuid */
            call_id?: string;
            file_url?: string;
            seconds?: number;
            transcript?: string | null;
            summary?: string | null;
            /** Format: date */
            suggested_followup_at?: string | null;
        };
        KycStatus: {
            /** @enum {string} */
            status?: "none" | "pending" | "approved" | "rejected";
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            result_at?: string | null;
            rejection_reason?: string | null;
        };
    };
    responses: {
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Plan limit or rule violation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Insufficient balance */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Too many tries or sends; see the Retry-After header when present */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Request body validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        version?: string;
                    };
                };
            };
        };
    };
    authSignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created; session cookie set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authConfirmEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Email confirmed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    authConfirmPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 307142 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Phone confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authResend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    channel: "email" | "sms" | "whatsapp";
                };
            };
        };
        responses: {
            /** @description Sent (or nothing to send because it is already confirmed) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authSignin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SigninRequest"];
            };
        };
        responses: {
            /** @description Signed in; session cookie set. If `confirmed` is false, show the confirm screen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authSignout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authForgot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Email or phone number */
                    login: string;
                };
            };
        };
        responses: {
            /** @description Code sent if the account exists */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    authReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Email or phone number */
                    login: string;
                    code: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plans?: components["schemas"]["Plan"][];
                        intro_eligible?: boolean;
                    };
                };
            };
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. Only `plan` is set on Free. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changeSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanChangeRequest"];
            };
        };
        responses: {
            /** @description Done */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanQuote"];
                };
            };
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    quoteSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanQuote"];
                };
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWalletActivity: {
        parameters: {
            query?: {
                /** @description next_cursor from the previous page */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        activity?: components["schemas"]["LedgerEntry"][];
                        /** @description Empty when there are no more entries */
                        next_cursor?: string;
                    };
                };
            };
        };
    };
    getWalletStatement: {
        parameters: {
            query?: {
                /** @description YYYY-MM; defaults to the current month */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    startTopup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopupRequest"];
            };
        };
        responses: {
            /** @description Send the rep to payment_url */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopupResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getTopup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reference?: string;
                        /** @enum {string} */
                        status?: "pending" | "succeeded" | "failed";
                        /** Format: int64 */
                        amount_microdollars?: number;
                        /** Format: date-time */
                        created_at?: string;
                    };
                };
            };
            /** @description Not this rep's top-up */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchNumbers: {
        parameters: {
            query?: {
                area_code?: string;
                country?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available numbers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        numbers?: components["schemas"]["AvailableNumber"][];
                    };
                };
            };
        };
    };
    listMyNumbers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        numbers?: components["schemas"]["RentedNumber"][];
                    };
                };
            };
        };
    };
    cancelNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                numberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setDefaultNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                numberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLeadLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lists: components["schemas"]["LeadList"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteLeadList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such list */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    checkImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description What the upload would do */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportCheck"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description File over 2 MB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"] & Record<string, never>;
            };
        };
        responses: {
            /** @description The lists created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lists: components["schemas"]["LeadList"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description File over 2 MB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listScripts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        scripts: components["schemas"]["Script"][];
                        /** @description The fill-in words a script can use, like {first_name} */
                        fields: string[];
                        /**
                         * Format: date
                         * @description On Free, the day the script stops showing on the call screen (2 months after sign-up). Null on Starter and Pro.
                         */
                        on_screen_free_until: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createScript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Script"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateScript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scriptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptRequest"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Script"];
                };
            };
            /** @description No such script, or one of the lists doesn't exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteScript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scriptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such script */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    startCall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCallRequest"];
            };
        };
        responses: {
            /** @description Call started; includes short-lived Telnyx token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartCallResponse"];
                };
            };
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
        };
    };
    saveOutcome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                callId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    endCall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                callId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startDialer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    list_id: string;
                };
            };
        };
        responses: {
            /** @description Session started */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pauseDialer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paused */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    skipDialer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skipped */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stopDialer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopped */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFollowups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        followups?: components["schemas"]["Followup"][];
                    };
                };
            };
        };
    };
    listHistory: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
        };
    };
    getRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                callId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
        };
    };
    getKycStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStatus"];
                };
            };
        };
    };
    startKyc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Smile ID session URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url?: string;
                    };
                };
            };
        };
    };
    createPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-time code (5 min TTL) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code?: string;
                        qr_url?: string;
                        /** Format: date-time */
                        expires_at?: string;
                    };
                };
            };
        };
    };
    joinPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Joined; Telnyx WebRTC token for phone leg */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token?: string;
                    };
                };
            };
        };
    };
    telnyxWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    paystackWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signature missing or wrong */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stripeWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signature missing or wrong */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    smileidWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListKyc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
